version: "3.7"

services:
  portfolio:
    image: pscamodio/portfolio
    container_name: portfolio
    restart: unless-stopped
    ports:
      - 3000:3000

  caddy: 
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy/caddy_data:/data
      - $PWD/caddy/caddy_config:/config

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

